import styled from '@emotion/styled';
import Head from 'next/head';
import { PropsWithChildren } from 'react';

interface Props {
  title?: string;
}

const DEFAULT_TITLE = process.env.NOTION_TITLE ?? '';

export const CommonLayout = ({ title, children }: PropsWithChildren<Props>) => {
  return (
    <>
      <Head>
        <title>{title ? `${title}-${DEFAULT_TITLE}` : DEFAULT_TITLE}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RootLayout>
        <Header>Header</Header>
        <Contents>{children}</Contents>
        <Footer>Footer</Footer>
      </RootLayout>
    </>
  );
};

const RootLayout = styled.div``;
const Header = styled.header``;
const Contents = styled.div``;
const Footer = styled.footer``;
